export const users = [
    {
        "id":0,
        "name":"Jan",
        "lastName":"Kowalski",
        "email":"jk@jk.pl",
        "date":"12-12-2012"
    },
    {
        "id":1,
        "name":"Maciej",
        "lastName":"Nowak",
        "email":"mn@mn.pl",
        "date":"15-12-2015"
    },{
        "id":2,
        "name":"Darek",
        "lastName":"Cichocki",
        "email":"dc@dc.pl",
        "date":"15-01-2001"
    },
];